name: Dart CI

on:
  push:
    branches: [ '*' ]
  pull_request:
    branches: [ '*' ]

jobs:
  codacy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2
        
      - name: Run Codacy CLI
        uses: codacy/codacy-cli-v2-action@main
        with:
          project_token: ${{ secrets.CODACY_PROJECT_TOKEN }}
          tool: dartanalyzer
          upload_report: true